CREATE TABLE teacher (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  surname VARCHAR(128) NOT NULL,
  username VARCHAR(128) NOT NULL,
  title VARCHAR(5) NOT NULL,
  password VARCHAR(15) NOT NULL
);

